name: hust_chill_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^7.6.4
  injectable: ^2.3.2

  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  intl: ^0.20.2

  google_fonts: ^6.3.0
  auto_size_text: ^3.0.0
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  flutter_svg: ^2.1.0
  lottie: ^3.2.0
  logger: ^2.6.0
  shimmer: ^3.0.0
  confetti: ^0.8.0

  # Realtime (nếu dùng Node)
  socket_io_client: ^2.0.3
  pinput: ^5.0.2
  flashy_tab_bar2: ^0.0.10
  dartz: ^0.10.1
  flutter_dotenv: ^5.2.1
  retrofit: 4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  freezed: ^2.4.5
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  retrofit_generator: 7.0.8
  flutter_lints: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/animation/
    - .env
